// This is motion 'Weight_Lifting_1' translated from json file 

#include <roki2met.h>
int frameCount;

void main(){

// page 0
  frameCount = 50;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 86, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 340, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 681, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 340, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 86, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 0, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 86, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 340, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 681, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 340, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 86, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfWaitFrame( frameCount );
// page 0 clone 1
  frameCount = 10;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 0, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 0, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfWaitFrame( frameCount );
// page 0 clone 4
  frameCount = 100;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 196, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 3342, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 6684, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 3342, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 196, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 307, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 0, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 196, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 3342, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 6684, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 3342, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 196, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 307, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfWaitFrame( frameCount );
// page 0 clone 5
  frameCount = 50;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 196, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 3342, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 6684, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 3342, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 196, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 307, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 1228, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 196, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 3342, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 6684, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 3342, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 196, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 307, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 1228, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfWaitFrame( frameCount );
// page 0 clone 6
  frameCount = 20;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 196, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 3342, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 6684, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 3342, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 196, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 4094, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, -307, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 1228, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 196, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 3342, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 6684, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 3342, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 196, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 4094, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, -307, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 1228, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfWaitFrame( frameCount );
// page 0 clone 7
  frameCount = 50;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 196, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 3342, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 6684, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 3342, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 196, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 4094, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, -307, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 1228, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 196, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 3342, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 6684, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 3342, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 196, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 4094, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, -307, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 1228, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfWaitFrame( frameCount );
// page 0 clone 8
  frameCount = 100;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 4094, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, -307, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 1228, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 0, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 4094, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, -307, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 1228, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfWaitFrame( frameCount );
}

