// This is motion 'Dance_5' translated from json file 

#include <roki2met.h>
int frameCount;

void main(){

// page 0
  frameCount = 10;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 0, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 0, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfWaitFrame( frameCount );
// page 0 clone 1
  frameCount = 20;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, -153, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, -153, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 0, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 153, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 153, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, -3379, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfWaitFrame( frameCount );
// page 0 clone 2
  frameCount = 10;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, -153, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, -153, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, -768, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 0, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 153, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 153, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, -768, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, -3379, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfWaitFrame( frameCount );
// page 0 clone 3
  frameCount = 10;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, -153, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 153, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, -768, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 0, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 153, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, -153, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, -768, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, -3379, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfWaitFrame( frameCount );
// page 0 clone 4
  frameCount = 10;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, -153, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 153, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 768, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 0, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 153, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, -153, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 768, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, -3379, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfWaitFrame( frameCount );
// page 0 clone 5
  frameCount = 10;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, -153, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, -153, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 768, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 0, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 153, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 153, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 768, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, -3379, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfWaitFrame( frameCount );
// page 0 clone 6
  frameCount = 10;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, -153, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, -153, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, -768, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 0, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 153, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 153, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, -768, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, -3379, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfWaitFrame( frameCount );
// page 0 clone 7
  frameCount = 10;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, -153, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 153, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, -768, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 0, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 153, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, -153, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, -768, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, -3379, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfWaitFrame( frameCount );
// page 0 clone 8
  frameCount = 10;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, -153, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 153, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 768, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 0, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 153, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, -153, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 768, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, -3379, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfWaitFrame( frameCount );
// page 0 clone 9
  frameCount = 10;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, -153, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, -153, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 768, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 0, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 153, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 153, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 768, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, -3379, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfWaitFrame( frameCount );
// page 0 clone 10
  frameCount = 10;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, -153, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, -153, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, -768, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 0, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 153, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 153, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, -768, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, -3379, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfWaitFrame( frameCount );
// page 0 clone 11
  frameCount = 10;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, -153, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 153, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, -768, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 0, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 153, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, -153, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, -768, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, -3379, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfWaitFrame( frameCount );
// page 0 clone 12
  frameCount = 10;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, -153, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 153, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 0, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 153, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, -153, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, -3379, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfWaitFrame( frameCount );
// page 0 clone 13
  frameCount = 10;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 0, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 0, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfWaitFrame( frameCount );
}

