// This is motion 'Dance_6' translated from json file 

#include <roki2met.h>
int frameCount;

void main(){

// page 0
  frameCount = 10;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 340, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 0, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 0, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 340, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfWaitFrame( frameCount );
// page 1
  frameCount = 20;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, -4, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 2233, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 4389, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 2156, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, -4, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 2764, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, -3840, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 614, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 1075, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, -4, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 2233, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 4389, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 2156, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, -4, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 2764, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, -3840, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 614, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 1075, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfWaitFrame( frameCount );
// page 2
  frameCount = 20;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 465, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 2500, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 4909, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 2406, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 465, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 3840, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, -3840, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, -460, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 1075, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, -465, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 2500, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 4909, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 2406, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, -465, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 1996, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, -3840, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, -460, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 1075, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfWaitFrame( frameCount );
// page 1 clone 1
  frameCount = 20;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, -4, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 2233, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 4389, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 2156, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, -4, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 2764, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, -3840, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 614, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 1075, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, -4, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 2233, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 4389, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 2156, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, -4, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 2764, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, -3840, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 614, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 1075, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfWaitFrame( frameCount );
// page 4
  frameCount = 20;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, -465, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 2500, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 4909, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 2406, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, -465, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 1996, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, -3840, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, -460, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 1075, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 465, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 2500, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 4909, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 2406, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 465, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 3840, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, -3840, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, -460, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 1075, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfWaitFrame( frameCount );
// page 1 clone 2
  frameCount = 20;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, -4, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 2233, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 4389, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 2156, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, -4, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 2764, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, -3840, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 614, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 1075, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, -4, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 2233, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 4389, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 2156, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, -4, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 2764, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, -3840, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 614, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 1075, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfWaitFrame( frameCount );
// page 2 clone 1
  frameCount = 30;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 465, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 2500, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 4909, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 2406, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 465, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 3840, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, -3840, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, -460, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 1075, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, -465, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 2500, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 4909, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 2406, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, -465, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 1996, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, -3840, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, -460, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 1075, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfWaitFrame( frameCount );
// page 1 clone 3
  frameCount = 20;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, -4, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 2233, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 4389, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 2156, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, -4, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 2764, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, -3840, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 614, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 1075, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, -4, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 2233, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 4389, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 2156, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, -4, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 2764, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, -3840, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 614, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 1075, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfWaitFrame( frameCount );
// page 4 clone 1
  frameCount = 30;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, -465, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 2500, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 4909, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 2406, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, -465, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 1996, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, -3840, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, -460, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 1075, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 465, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 2500, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 4909, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 2406, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 465, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 3840, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, -3840, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, -460, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 1075, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfWaitFrame( frameCount );
// page 1 clone 3
  frameCount = 20;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, -4, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 2233, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 4389, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 2156, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, -4, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 2764, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, -3840, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 614, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 1075, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, -4, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 2233, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 4389, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 2156, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, -4, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 2764, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, -3840, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 614, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 1075, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfWaitFrame( frameCount );
// page 2 clone 2
  frameCount = 30;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 465, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 2500, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 4909, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 2406, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 465, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 3840, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, -3840, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, -460, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 1075, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, -465, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 2500, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 4909, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 2406, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, -465, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 1996, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, -3840, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, -460, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 1075, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfWaitFrame( frameCount );
// page 1 clone 4
  frameCount = 20;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, -4, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 2233, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 4389, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 2156, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, -4, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 2764, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, -3840, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 614, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 1075, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, -4, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 2233, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 4389, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 2156, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, -4, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 2764, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, -3840, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 614, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 1075, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfWaitFrame( frameCount );
// page 4 clone 2
  frameCount = 30;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, -465, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 2500, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 4909, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 2406, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, -465, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 1996, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, -3840, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, -460, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 1075, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 465, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 2500, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 4909, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 2406, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 465, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 3840, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, -3840, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, -460, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 1075, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfWaitFrame( frameCount );
// page 5
  frameCount = 20;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 0, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 0, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfWaitFrame( frameCount );
}

