// This is motion 'Dance_7-1' translated from json file 

#include <roki2met.h>
int frameCount;

void main(){

// page 0
  frameCount = 10;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 0, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 0, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfWaitFrame( frameCount );
// page 1
  frameCount = 10;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, -2304, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 1075, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 0, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, -2304, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 1075, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfWaitFrame( frameCount );
// page 2
  frameCount = 5;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 5068, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, -2304, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, -1075, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 1075, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 0, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, -2304, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 1075, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfWaitFrame( frameCount );
// page 3
  frameCount = 10;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 5068, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, -2304, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, -1075, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 1075, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 0, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, -2304, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 1075, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfWaitFrame( frameCount );
// page 4
  frameCount = 5;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, -2304, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 1075, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 0, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, -2304, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 1075, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfWaitFrame( frameCount );
// page 5
  frameCount = 5;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, -2304, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 1075, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 0, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 5068, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, -2304, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, -1075, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 1075, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfWaitFrame( frameCount );
// page 6
  frameCount = 10;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, -2304, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 1075, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 0, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 5068, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, -2304, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, -1075, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 1075, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfWaitFrame( frameCount );
// page 7
  frameCount = 5;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 2304, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, -2764, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 9216, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 0, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 5068, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, -2304, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, -1075, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 1075, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfWaitFrame( frameCount );
// page 8
  frameCount = 50;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 3379, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, -2764, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 9216, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 0, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 5068, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, -2304, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, -1075, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 1075, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfWaitFrame( frameCount );
// page 9
  frameCount = 10;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 3379, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, -2764, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 9216, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 0, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, -2304, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 1075, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfWaitFrame( frameCount );
// page 10
  frameCount = 5;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 3379, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, -2764, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 9216, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 0, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 2304, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, -2764, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 9216, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfWaitFrame( frameCount );
// page 11
  frameCount = 10;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 3072, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, -2764, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 9216, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 0, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 3072, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, -2764, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 9216, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfWaitFrame( frameCount );
// page 12
  frameCount = 10;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 1075, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, -2764, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 9216, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 0, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 3379, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, -2764, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 9216, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfWaitFrame( frameCount );
// page 13
  frameCount = 5;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 1075, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, -2764, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 119, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 0, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 3379, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, -2764, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 9216, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfWaitFrame( frameCount );
// page 14
  frameCount = 10;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 1075, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, -2764, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 119, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 0, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 1075, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, -2764, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 9216, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfWaitFrame( frameCount );
// page 15
  frameCount = 5;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 1075, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, -2764, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 119, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 0, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 1075, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, -2764, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 119, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfWaitFrame( frameCount );
// page 16
  frameCount = 10;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 1075, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, -2764, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 119, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 0, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 1075, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, -2764, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 119, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfWaitFrame( frameCount );
// page 17
  frameCount = 10;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, -2764, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 119, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 0, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 1075, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, -2764, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 119, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfWaitFrame( frameCount );
// page 18
  frameCount = 10;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, -2764, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, -1311, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 0, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 1075, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, -2764, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 119, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfWaitFrame( frameCount );
// page 19
  frameCount = 10;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 1689, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, -2764, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, -1311, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 0, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 1075, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, -2764, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 119, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfWaitFrame( frameCount );
// page 20
  frameCount = 10;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 1689, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, -2764, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, -1311, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 0, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, -2764, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 119, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfWaitFrame( frameCount );
// page 21
  frameCount = 10;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 1689, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, -2764, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, -1311, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 0, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, -2764, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, -1311, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfWaitFrame( frameCount );
// page 22
  frameCount = 10;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 1689, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, -2764, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, -1311, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 0, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 1689, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, -2764, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, -1311, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfWaitFrame( frameCount );
// page 23
  frameCount = 20;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 921, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, -1536, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 1689, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, -2764, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, -1311, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 921, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, -1536, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 1689, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, -2764, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, -1311, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfWaitFrame( frameCount );
// page 24
  frameCount = 20;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 1689, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, -2764, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, -1311, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 0, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 1689, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, -2764, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, -1311, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfWaitFrame( frameCount );
// page 25
  frameCount = 20;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 921, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, -1536, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 1689, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, -2764, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, -1311, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 921, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, -1536, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 1689, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, -2764, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, -1311, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfWaitFrame( frameCount );
// page 26
  frameCount = 20;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 1689, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, -2764, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, -1311, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 0, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 1689, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, -2764, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, -1311, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfWaitFrame( frameCount );
// page 27
  frameCount = 10;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, -2764, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, -1311, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 0, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, -2764, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, -1311, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfWaitFrame( frameCount );
// page 28
  frameCount = 10;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, -153, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, -2764, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 2304, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, -153, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, -2764, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 2304, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfWaitFrame( frameCount );
// page 29
  frameCount = 20;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 768, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, -1536, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, -2764, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, -1311, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 768, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, -1536, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, -2764, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, -1311, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfWaitFrame( frameCount );
// page 30
  frameCount = 20;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, -153, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, -2764, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 2304, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, -153, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, -2764, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 2304, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfWaitFrame( frameCount );
// page 31
  frameCount = 20;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 768, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, -1536, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, -2764, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, -1311, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 768, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, -1536, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, -2764, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, -1311, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfWaitFrame( frameCount );
// page 32
  frameCount = 20;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, -153, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, -2764, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 2304, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, -153, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, -2764, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 2304, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfWaitFrame( frameCount );
}

