// This is motion 'Kick_Right_v2' translated from json file 

#include <roki2met.h>
int frameCount;

void main(){

// page 0
  frameCount = 20;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 4094, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 340, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 384, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 0, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 4094, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 340, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 384, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 1884, frameCount );
  sfWaitFrame( frameCount );
// page 1
  frameCount = 20;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 800, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 428, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 857, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 428, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 800, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 4094, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 340, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 384, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, -646, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 638, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 1277, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 638, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, -646, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 4094, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 340, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 384, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 1884, frameCount );
  sfWaitFrame( frameCount );
// page 2
  frameCount = 10;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 916, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 1734, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 3469, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 1734, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 916, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 4094, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 340, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 384, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, -800, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 638, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 1277, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 638, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, -646, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 4094, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 340, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 384, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 1884, frameCount );
  sfWaitFrame( frameCount );
// page 3
  frameCount = 20;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 916, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 2460, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 3477, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 1016, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 916, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 4094, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 340, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 384, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, -800, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 638, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 1277, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 638, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, -646, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 4094, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 340, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 384, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 1884, frameCount );
  sfWaitFrame( frameCount );
// page 4
  frameCount = 2;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 916, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 1734, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 3469, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 1734, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 916, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 4094, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 340, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 384, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, -800, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 638, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 1277, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 638, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, -646, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 4094, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 340, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 384, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 1884, frameCount );
  sfWaitFrame( frameCount );
// page 5
  frameCount = 1;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 984, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, -798, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 2162, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 2967, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 984, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 4094, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 340, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 384, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, -800, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 638, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 1277, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 638, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, -646, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 4094, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 340, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 384, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 1884, frameCount );
  sfWaitFrame( frameCount );
// page 5 clone 1
  frameCount = 5;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 984, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, -798, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 2162, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 2967, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 984, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 4094, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 340, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 384, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, -800, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 638, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 1277, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 638, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, -646, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 4094, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 340, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 384, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 1884, frameCount );
  sfWaitFrame( frameCount );
// page 6
  frameCount = 20;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 916, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 1734, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 3469, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 1734, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 916, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 4094, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 340, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 384, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, -800, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 638, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 1277, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 638, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, -646, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 4094, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 340, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 384, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 1884, frameCount );
  sfWaitFrame( frameCount );
// page 7
  frameCount = 10;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 800, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 428, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 857, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 428, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 800, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 4094, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 340, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 384, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, -646, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 638, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 1277, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 638, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, -646, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 4094, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 340, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 384, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 1884, frameCount );
  sfWaitFrame( frameCount );
// page 8
  frameCount = 20;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 4094, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 340, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 384, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 0, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 4094, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 340, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 384, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 1884, frameCount );
  sfWaitFrame( frameCount );
}

