// This is motion 'Kick_v1' translated from json file 

#include <roki2met.h>
int frameCount;

void main(){

// page 0
  frameCount = 20;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 340, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 0, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 0, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 340, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfWaitFrame( frameCount );
// page 1
  frameCount = 20;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 738, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 1001, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 2004, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 1001, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 738, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 340, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 0, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, -629, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 1072, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 2144, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 1072, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, -629, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 340, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfWaitFrame( frameCount );
// page 2
  frameCount = 10;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 916, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 1734, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 3469, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 1734, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 916, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 340, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 0, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, -827, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 1046, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 2092, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 1046, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, -674, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 340, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfWaitFrame( frameCount );
// page 3
  frameCount = 20;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 916, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 2460, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 3477, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 1016, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 916, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 340, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 0, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, -827, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 1046, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 2092, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 1046, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, -674, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 340, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfWaitFrame( frameCount );
// page 4
  frameCount = 1;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 916, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 1734, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 3469, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 1734, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 916, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 340, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 0, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, -827, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 1046, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 2092, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 1046, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, -674, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 340, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfWaitFrame( frameCount );
// page 5
  frameCount = 1;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 984, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, -30, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 2162, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 2967, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 984, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 340, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 0, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, -827, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 1046, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 2092, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 1046, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, -674, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 340, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfWaitFrame( frameCount );
// page 5 clone 1
  frameCount = 5;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 984, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, -804, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 2162, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 2967, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 984, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 340, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 0, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, -827, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 1046, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 2092, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 1046, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, -674, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 340, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfWaitFrame( frameCount );
// page 6
  frameCount = 20;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 916, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 1734, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 3469, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 1734, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 916, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 340, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 0, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, -827, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 1046, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 2092, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 1046, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, -674, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 340, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfWaitFrame( frameCount );
// page 7
  frameCount = 10;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 738, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 1001, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 2004, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 1001, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 738, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 340, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 0, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, -629, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 1072, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 2144, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 1072, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, -629, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 340, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfWaitFrame( frameCount );
// page 8
  frameCount = 20;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 340, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 0, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 0, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 340, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfWaitFrame( frameCount );
}

