// This is motion 'Roki_2_Get_UP_Face_Up' translated from json file 

#include <roki2met.h>
int frameCount;

void main(){

// page 0
  frameCount = 20;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 0, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 0, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HAND, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HAND, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAW, 0, frameCount );
  sfPoseGroup( MASK_LEFT_CLAW, 0, frameCount );
  sfWaitFrame( frameCount );
// page 2
  frameCount = 30;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 3532, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 5376, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, -2457, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 2150, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, -3072, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 7680, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 2764, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 3534, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 5376, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, -2457, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 2150, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, -3072, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 7680, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 2764, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HAND, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HAND, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAW, 0, frameCount );
  sfPoseGroup( MASK_LEFT_CLAW, 0, frameCount );
  sfWaitFrame( frameCount );
// page 4 clone 2
  frameCount = 20;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 3532, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 3717, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, -2274, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, -3072, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 7680, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 4254, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 3532, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 3655, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, -2274, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, -3072, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 7680, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 4316, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 4712, frameCount );
  sfPoseGroup( MASK_RIGHT_HAND, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HAND, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAW, 0, frameCount );
  sfPoseGroup( MASK_LEFT_CLAW, 0, frameCount );
  sfWaitFrame( frameCount );
// page 7
  frameCount = 50;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 102, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 1721, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 3445, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 1721, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 102, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 4094, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 399, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 102, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 1721, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 3445, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 1721, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 102, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 4094, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 399, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HAND, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HAND, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAW, 0, frameCount );
  sfPoseGroup( MASK_LEFT_CLAW, 0, frameCount );
  sfWaitFrame( frameCount );
// page 9
  frameCount = 10;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 5145, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 384, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 0, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 5145, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 384, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HAND, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HAND, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAW, 0, frameCount );
  sfPoseGroup( MASK_LEFT_CLAW, 0, frameCount );
  sfWaitFrame( frameCount );
}

