// This is motion 'Soccer_Kick_Forward_Right_Leg' translated from json file 

#include <roki2met.h>
int frameCount;

void main(){

// page 0
  frameCount = 14;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 844, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 1536, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 768, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 1536, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 307, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, -768, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 844, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 1536, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 768, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 1536, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 307, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, -768, frameCount );
  sfWaitFrame( frameCount );
// page 1
  frameCount = 40;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 640, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 728, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 1536, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 768, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, -307, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 1536, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 307, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, -768, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, -660, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 2380, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 4070, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 1751, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 460, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 1536, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 307, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, -768, frameCount );
  sfWaitFrame( frameCount );
// page 2
  frameCount = 20;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 179, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 2241, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 2638, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, -1110, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, -614, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 3072, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 307, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 0, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, -660, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 2380, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 4070, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 1751, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 460, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 3072, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 1075, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, -2304, frameCount );
  sfWaitFrame( frameCount );
// page 3
  frameCount = 3;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 2293, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 4634, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 1362, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, -614, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 3072, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 307, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 0, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, -660, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 2380, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 4070, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 1751, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 614, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 3072, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 1075, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, -2304, frameCount );
  sfWaitFrame( frameCount );
// page 4
  frameCount = 3;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 62, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, -2219, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 3072, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, -614, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 3072, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 307, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, -2304, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, -691, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 3214, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 4022, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 1104, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 614, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 3072, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 1075, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 0, frameCount );
  sfWaitFrame( frameCount );
// page 5
  frameCount = 2;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, -202, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, -4764, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, -2058, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 4435, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, -640, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 256, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 2803, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 79, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 4644, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 7117, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 4360, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 339, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 459, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 2267, frameCount );
  sfWaitFrame( frameCount );
// page 6
  frameCount = 50;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, -202, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, -4764, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, -2058, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 4435, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, -640, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 256, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 2803, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 79, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 4644, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 7117, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 4360, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 339, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 459, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 2267, frameCount );
  sfWaitFrame( frameCount );
// page 7
  frameCount = 50;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, -202, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, -3108, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, -2737, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 213, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, -640, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 256, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 2803, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 211, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 2224, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 2638, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 413, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 339, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 459, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 2267, frameCount );
  sfWaitFrame( frameCount );
// page 8
  frameCount = 50;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, -202, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, -978, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 1222, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 2393, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, -614, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, -640, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 256, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, -1886, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 79, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 2976, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 3211, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 413, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 614, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 339, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 459, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, -52, frameCount );
  sfWaitFrame( frameCount );
// page 9
  frameCount = 50;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, -202, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 794, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 4277, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 3529, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, -640, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 256, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 2803, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 479, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 3230, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 1771, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, -1353, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 339, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 459, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 2267, frameCount );
  sfWaitFrame( frameCount );
// page 10
  frameCount = 50;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, -614, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 794, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 4277, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 3967, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, -614, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, -640, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 256, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 2803, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 614, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 3021, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 1771, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, -798, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 614, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 339, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 459, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 2267, frameCount );
  sfWaitFrame( frameCount );
// page 11
  frameCount = 6;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, -614, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 794, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 4277, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 3967, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, -614, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, -640, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 256, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 2803, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 614, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 4600, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 7160, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 2982, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 614, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 339, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 459, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 2267, frameCount );
  sfWaitFrame( frameCount );
// page 12
  frameCount = 6;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, -614, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 1494, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 3849, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 2393, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, -614, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, -640, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 256, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 2803, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 374, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 1689, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 4509, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 2832, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 614, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 339, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 459, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 2267, frameCount );
  sfWaitFrame( frameCount );
// page 13
  frameCount = 40;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 844, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 1536, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 768, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 1536, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 307, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, -768, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 844, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 1536, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 768, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 1536, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 307, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, -768, frameCount );
  sfWaitFrame( frameCount );
// page 14
  frameCount = 15;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 921, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 1536, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 768, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 3072, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 307, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, -1228, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 921, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 1536, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 768, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 3072, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 307, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, -1228, frameCount );
  sfWaitFrame( frameCount );
}

