// This is motion 'Soccer_Small_Jump_Forward' translated from json file 

#include <roki2met.h>
int frameCount;

void main(){

// page 0
  frameCount = 10;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, -76, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 2274, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 4551, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 2274, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, -153, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 4608, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 460, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, -1536, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, -76, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 2274, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 4551, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 2274, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, -153, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 4608, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 460, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, -1536, frameCount );
  sfWaitFrame( frameCount );
// page 1
  frameCount = 8;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, -76, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 2918, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 6144, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 3686, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, -153, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 4608, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 460, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 0, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, -76, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 2918, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 6144, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 3686, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, -153, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 4608, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 460, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 0, frameCount );
  sfWaitFrame( frameCount );
// page 2
  frameCount = 4;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, -76, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 3072, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 3840, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 1536, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, -153, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 4608, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 460, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 2304, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, -76, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 3072, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 3840, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 1536, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, -153, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 4608, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 460, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 2304, frameCount );
  sfWaitFrame( frameCount );
// page 3
  frameCount = 1;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, -76, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 3072, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 6144, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 2967, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, -153, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 4608, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 460, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, -1536, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, -76, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 3072, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 6144, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 2967, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, -153, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 4608, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 460, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, -1536, frameCount );
  sfWaitFrame( frameCount );
// page 4
  frameCount = 3;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, -76, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 3072, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 6144, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 3225, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, -153, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 4608, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 460, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, -1536, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, -76, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 3072, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 6144, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 3225, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, -153, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 4608, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 460, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, -1536, frameCount );
  sfWaitFrame( frameCount );
// page 5
  frameCount = 10;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, -76, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 2121, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 4551, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 2274, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, -153, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 4608, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 460, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, -1536, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, -76, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 2121, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 4551, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 2274, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, -153, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 4608, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 460, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, -1536, frameCount );
  sfWaitFrame( frameCount );
// page 6
  frameCount = 10;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, -76, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 768, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 1536, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 768, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 3072, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 460, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, -1228, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, -76, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 768, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 1536, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 768, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 3072, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 460, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, -1228, frameCount );
  sfWaitFrame( frameCount );
}

