// This is motion 'TropleJumpForFIRA2019' translated from json file 

#include <roki2met.h>
int frameCount;

void main(){

// page 0
  frameCount = 10;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 0, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 0, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 0, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, 0, frameCount );
  sfWaitFrame( frameCount );
// page 1
  frameCount = 20;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 3072, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 6144, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 3456, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 460, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, -1022, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 3072, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 6144, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 3456, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 460, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, -1024, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, -921, frameCount );
  sfWaitFrame( frameCount );
// page 2
  frameCount = 8;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 3840, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 6144, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 3072, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 460, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, -1022, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 3840, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 6144, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 3072, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 460, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, -1022, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, -921, frameCount );
  sfWaitFrame( frameCount );
// page 3
  frameCount = 4;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 3326, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 3840, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 1536, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 460, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 2304, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 3326, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 3840, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 1536, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 460, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 2304, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, -921, frameCount );
  sfWaitFrame( frameCount );
// page 4
  frameCount = 2;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 921, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, -307, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 307, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, -1996, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 460, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 3840, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 921, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, -307, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 307, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, -1996, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 460, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 3840, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, -921, frameCount );
  sfWaitFrame( frameCount );
// page 5
  frameCount = 1;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 1536, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, -1474, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, -2304, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 622, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 460, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, 5938, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 1536, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, -1474, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, -2304, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 622, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 460, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, 5938, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, -921, frameCount );
  sfWaitFrame( frameCount );
// page 6
  frameCount = 1;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 3429, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 7065, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 5191, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, -921, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 460, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, -3583, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 3429, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 7065, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 5191, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, -921, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 460, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, -3583, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, -921, frameCount );
  sfWaitFrame( frameCount );
// page 7
  frameCount = 2;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 3429, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 7065, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 5191, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, -921, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 460, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, -3583, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 3429, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 7065, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 5191, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, -921, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 460, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, -3583, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, -921, frameCount );
  sfWaitFrame( frameCount );
// page 8
  frameCount = 6;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 3993, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 7065, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 3072, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, -921, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 460, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, -4094, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 3993, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 7065, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 3072, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, -921, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 460, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, -4094, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, -921, frameCount );
  sfWaitFrame( frameCount );
// page 9
  frameCount = 50;
  sfPoseGroup( MASK_RIGHT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_FOOT_FRONT, 3072, frameCount );
  sfPoseGroup( MASK_RIGHT_KNEE, 6144, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP, 3456, frameCount );
  sfPoseGroup( MASK_RIGHT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_RIGHT_SHOULDER, 460, frameCount );
  sfPoseGroup( MASK_RIGHT_CLAVICLE, -1022, frameCount );
  sfPoseGroup( MASK_TORSO_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_FOOT_FRONT, 3072, frameCount );
  sfPoseGroup( MASK_LEFT_KNEE, 6144, frameCount );
  sfPoseGroup( MASK_LEFT_HIP, 3456, frameCount );
  sfPoseGroup( MASK_LEFT_HIP_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_PELVIC, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW, 0, frameCount );
  sfPoseGroup( MASK_LEFT_ELBOW_SIDE, 0, frameCount );
  sfPoseGroup( MASK_LEFT_SHOULDER, 460, frameCount );
  sfPoseGroup( MASK_LEFT_CLAVICLE, -1022, frameCount );
  sfPoseGroup( MASK_HEAD_ROTATE, 0, frameCount );
  sfPoseGroup( MASK_HEAD_TILT, -921, frameCount );
  sfWaitFrame( frameCount );
}

